"use client";

import { buildPyodideIndex, type PyodideIndex } from "@/lib/sandbox/packages";
import { baseRIndex, buildRIndex, type RIndex } from "@/lib/sandbox/runnable";

/**
 * Loads the package-availability indexes in the browser, once per page, lazily.
 *
 * Lazily and per language, because these files are not small: Pyodide's lock is
 * 113 KB and the WebR manifest is 253 KB (100 KB gzipped, 22,741 package names).
 * Fetching both on every chat page would be a real cost paid by every student,
 * including the majority whose conversation contains no code at all. So nothing
 * is fetched until a runnable block of that language actually exists.
 *
 * Every failure resolves to "we do not know" rather than rejecting. A missing
 * manifest must degrade to today's behaviour, which is to offer Run and let the
 * runtime report any problem, never to hide a button because a fetch failed.
 */

let pythonPromise: Promise<PyodideIndex | null> | null = null;
let rPromise: Promise<RIndex> | null = null;

export function loadPythonIndex(): Promise<PyodideIndex | null> {
  if (!pythonPromise) {
    pythonPromise = fetch("/runtimes/pyodide/pyodide-lock.json")
      .then((res) => (res.ok ? res.json() : null))
      .then((lock) => (lock ? buildPyodideIndex(lock) : null))
      .catch(() => null);
  }
  return pythonPromise;
}

export function loadRIndex(): Promise<RIndex> {
  if (!rPromise) {
    rPromise = fetch("/runtimes/webr-packages/available.json")
      .then((res) => (res.ok ? res.json() : null))
      .then((manifest) =>
        manifest && typeof manifest === "object"
          ? buildRIndex(manifest as { mirrored?: string[]; repo?: string[] })
          : baseRIndex(),
      )
      // No manifest on this server (public/runtimes is generated by
      // npm run setup:runtimes). baseRIndex knows the bundled set and nothing
      // else, so unmirrored packages come back "unknown" and stay runnable.
      .catch(() => baseRIndex());
  }
  return rPromise;
}

/** Test seam: forget the cached indexes. */
export function resetAvailabilityCache(): void {
  pythonPromise = null;
  rPromise = null;
}
