import streamlit as st

def render_sidebar():
    # App information
    st.sidebar.markdown("""
### Mantained By 
  - [Fadel Megahed](https://miamioh.edu/fsb/directory/?up=/directory/megahefm)   
  - [Joshua Ferris](https://miamioh.edu/fsb/directory/?up=/directory/ferrisj2)

### Version 
  2.0.0 (February 28, 2025)

### Key Features
  - Free to use
  - Chat with one of seven LLMs
  - Export chat to PDF
  
### Support & Funding
  - Farmer School of Business
  - US Bank
""")
    
    # A Button to show/hide the disclaimers and references
    if "show_info" not in st.session_state:
        st.session_state.show_info = False
    if st.sidebar.button("Toggle Disclaimers & References"):
        st.session_state.show_info = not st.session_state.show_info
    
    # Conditionally display the disclaimers and references
    if st.session_state.show_info:
        st.sidebar.markdown("""
### Disclaimers
- ChatISA is designed for educational purposes only.
- If you plan to use ChatISA for classwork, you must obtain approval from your instructor beforehand.
- Neither Miami University nor the Farmer School of Business can be held responsible for any content generated by this app.
- Always use ChatISA at your own risk and evaluate the accuracy of the generated answers.

### References
- **Prompt Engineering:** Adapted from [Assigning AI by Mollick and Mollic 2023](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4475995)
- **Streamlit App:** Adapted from [ChatGPT Apps with Streamlit](https://docs.streamlit.io/knowledge-base/tutorials/build-conversational-apps#build-a-chatgpt-like-app)
- **Our Code Repo:** [![Click here to access](https://img.shields.io/badge/view_source_code-gray?logo=github)](https://github.com/fmegahed/chatisa)
- **Our ArXiv Paper:** [ChatISA Paper](https://arxiv.org/pdf/2407.15010)
""")
