/**
 * GENERATED by scripts/make-deploy-bundle.mjs. Do not edit by hand; the next
 * bundle run overwrites it.
 *
 * The date shown in the site footer. It is written here as a string LITERAL
 * before `next build` runs, which is what freezes it: the literal is compiled
 * into the output, so every visitor sees the date this bundle was made rather
 * than the date they happened to open the app. The footer is a server
 * component, so `new Date()` would re-evaluate on every request and
 * `process.env` would be read at request time on a server that never had the
 * variable set. A literal has neither problem.
 *
 * Between bundle runs this holds the date of the last bundle, which is the
 * honest answer to "when was the running app last updated".
 */
export const BUILD_DATE = "August 23, 2026";
